kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vv-test-admin
  namespace: vv-test-4
subjects:
  - kind: Group
    name: "github:test-webops"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-test-4
  namespace: vv-test-4
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitops-test-4
  namespace: vv-test-4
subjects:
- kind: ServiceAccount
  name: gitops-test-4
  namespace: vv-test-4
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
