#!/bin/sh

set -o errexit
set -o pipefail

_checkenv(){
  missing=""
  for v in URL TEAM BASIC_AUTH_USERNAME BASIC_AUTH_PASSWORD FLY_VERSION CLUSTER GITHUB_ORG GITHUB_TEAMS; do
    vn="CONCOURSE_${v}"
    fv=""
    eval fv="\$$vn"
    if [ -z "${fv}" ]; then
      missing="${missing}\n\t${vn}"
    fi
  done
  if [ ! -z "${missing}" ]; then
    echo "missing environment variables:${missing}"
    exit 1
  fi
}

_tf() {
  if [ "${#}" != 2 ]; then return 1; fi
  if [ "${1}" != "apply" ] && [ "${1}" != "destroy" ]; then return 1; fi
  if [ ! -d "${2}" ]; then return 0; fi
  cd "${2}"
  echo ">>> creating pipeline resources for $(basename ${2})"
  (
    set -x
    terraform init
    terraform "${1}" -auto-approve | sed -E 's/((content|template):[[:space:]]+)".+"/\1<REDACTED>/'
  )
  cd $OLDPWD
}

_checkenv

apk add \
  --no-cache \
  --no-progress \
  curl

curl -Lso /tmp/fly-5.0.0-linux-amd64.tgz https://github.com/concourse/concourse/releases/download/v5.0.0/fly-5.0.0-linux-amd64.tgz
tar -xvf /tmp/fly-5.0.0-linux-amd64.tgz -C /usr/local/bin
chmod +x /usr/local/bin/fly


fly \
  -t live-1 \
  login \
  -k \
  -c ${CONCOURSE_URL} \
  -n ${CONCOURSE_TEAM} \
  -u ${CONCOURSE_BASIC_AUTH_USERNAME} \
  -p ${CONCOURSE_BASIC_AUTH_PASSWORD}

  fly -t live-1 sync

fly -t live-1 pipelines -a | awk '{ print $1; }' | sort > live-1_pipelines


echo "setting roles for moj team"



spawn "fly -t live-1 set-team -n moj -c ./roles.yml"
expect "apply configuration? [yN]"
send "y\r"
# expect eof

  

_team_path="pipelines/${CONCOURSE_CLUSTER}/${CONCOURSE_TEAM}"

find "${_team_path}" -iname '*.yaml' -exec basename {} \; | cut -d'.' -f1 | sort > git_pipelines

# for i in $(comm -23 live-1_pipelines git_pipelines); do
#   echo ">>> deleting pipeline '${i}'"
#   (
#     set -x
#     fly \
#       -t live-1 \
#       destroy-pipeline \
#       -n \
#       -p "${i}"
#   )

#   _tf destroy "${_team_path}/${i}"
# done

for i in $(cat git_pipelines); do
  _tf apply "${_team_path}/${i}"

  echo ">>> setting pipeline '${i}'"
  (
    set -x
    fly \
      -t live-1 \
      set-pipeline \
      -n moj \
      -p "${i}" \
      -c "${_team_path}/${i}.yaml"
    fly \
      -t live-1 \
      unpause-pipeline \
      -p "${i}"
  )
done
