#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# shellcheck source=.common.sh
# source "$(dirname ${BASH_SOURCE[0]})/.common.sh"

log() {
  _fg=''
  [ "${1}" = "red" ] && _fg='\033[0;31m'
  [ "${1}" = "blue" ] && _fg='\033[0;34m'
  [ "${1}" = "green" ] && _fg='\033[0;32m'
  shift
  # shellcheck disable=SC2145
  echo -e "${_fg}>>> ${@}\033[0m"
}

cluster="${PIPELINE_CLUSTER}"


echo ${cluster}
log green "applying for cluster ${cluster}"
( set -x; kubectl config use-context "${cluster}" ) || { log red "no context found, skipping ${cluster}" && exit 1; }
for _f in namespaces/vij-argocd.cloud-platform.service.justice.gov.uk/*; do
  if [ -d "${_f}" ]; then
    namespace="$(basename ${_f})"
    log blue "applying resources for namespace ${namespace} in ${cluster}"
    set -x;
    repourl=$(kubectl get ns ${namespace} -o json | jq -r '.metadata.annotations["cloud-platform.justice.gov.uk/source-code"]')
    # set the uri 
    
    apk add \
      --no-cache \
      --no-progress \
      curl \
      tar

    curl -Ls "https://github.com/concourse/concourse/releases/download/v${CONCOURSE_FLY_VERSION}/fly-${CONCOURSE_FLY_VERSION}-linux-amd64.tgz" | tar zxf - -C /usr/local/bin

    PIPELINE_NAME=${namespace}
    fly \
      -t current \
      login \
      -k \
      -c ${CONCOURSE_URL} \
      -n ${CONCOURSE_TEAM} \
      -u ${CONCOURSE_BASIC_AUTH_USERNAME} \
      -p ${CONCOURSE_BASIC_AUTH_PASSWORD}
    
    # fly set-pipeline
    # config as yaml
    # vars aas repo url and namespace
  fi
done
