apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: integration-test-helloworld
  namespace: vv-test-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: integration-test-app
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: integration-test-svc
  namespace: vv-test-2
  labels:
    app: integration-test-svc
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: integration-test-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: integration-test-app-ing
  namespace: vv-test-2
spec:
  tls:
  - hosts:
    - test-git.apps.spinnaker.cloud-platform.service.justice.gov.uk
    secretName: hello-world-ssl
  rules:
  - host: test-git-spinnaker.apps.spinnaker.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: integration-test-svc
          servicePort: 80

