apiVersion: v1
kind: Namespace
metadata:
  name: vv-test-3
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "dev"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "cloud-platform"
    cloud-platform.justice.gov.uk/application: "app-test"
    cloud-platform.justice.gov.uk/owner: "vijay.veeranki: cloud-platform"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/poornima-moj/cloud-platform-gitops-test3"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vv-test-admin
  namespace: vv-test-3
subjects:
  - kind: Group
    name: "github:test-webops"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-vv-test-3
  namespace: vv-test-3
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitops-vv-test-3
  namespace: vv-test-3
subjects:
- kind: ServiceAccount
  name: gitops-vv-test-3
  namespace: vv-test-3
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: vv-test-3
spec:
  limits:
  - default:
      cpu: 250m
      memory: 500Mi
    defaultRequest:
      cpu: 10m
      memory: 100Mi
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: vv-test-3
spec:
  hard:
    requests.cpu: 3000m
    requests.memory: 6Gi
    limits.cpu: 6000m
    limits.memory: 12Gi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default
  namespace: vv-test-3
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingress-controllers
  namespace: vv-test-3
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          component: ingress-controllers
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: integration-test-helloworld
  namespace: vv-test-3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: integration-test-app
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: integration-test-svc
  namespace: vv-test-3
  labels:
    app: integration-test-svc
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: integration-test-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: integration-test-app-ing
  namespace: vv-test-3
spec:
  tls:
  - hosts:
    - vv-test-3.apps.spinnaker.cloud-platform.service.justice.gov.uk
    secretName: hello-world-ssl
  rules:
  - host: vv-test-3-spinnaker.apps.spinnaker.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: integration-test-svc
          servicePort: 80

